### ISSUE TITLE
How to handle not existing VEVENT fields

### ISSUE THREAD

**Issue by WK-GiHu** [pyproper/.icstocsv#2]
@pyproper 

>I tried to uncomment # csv_writer.writerow(writerow) but it only prints the tablehead. I also tried the print(writerow) but it prints it not in a clean format. 
1. You have to decide
    - [ ] I want to skip the whole `VEVENT` if it's invalid
    - [x] I want to replace not existant fields with `'Undefinde!'`

2. Edit [icscsv.py](https://github.com/pyproper/.icstocsv/blob/master/icscsv.py) to show your attempt.

### Update allways your [icscsv.py](https://github.com/pyproper/.icstocsv/blob/master/icscsv.py) so i can review it.

**Comment by pyproper** [comment]
Updated and working as intended now

**Comment by WK-GiHu** [comment]
@pyproper 

Please accept the [SO Answer](https://stackoverflow.com/questions/59958941)
